youtube:
  cookies_file: "./cookies/yt_11.txt" #zhaojson71@gmail.com
  video_limit_before_rest: 50  # 成功下载多少个视频后休息（0 表示不限制）
  concurrent_fragments: 2  # 并发下载片段数，提高下载速度
  sleep_interval_seconds: 30  # 睡眠间隔时间（秒）
  video_limit_rest_duration: 120  # 休息时长（分钟），默认1小时，实际休息时间会在此基础上随机增加 0-10%
  video_ids: # 3
    - "udMyxEP76yo"
    - "hstBiVD7pik"
    - "VLMXmjt8tN4"
    - "SOWFIxSy2eU"
    - "wxv86HZMe_w"
    - "yPuw76DdFzw"
    - "VdN6dlCT6r4"
    - "RwEdjqkbkHo"
    - "8QbdvkDsn2I"
    - "-1cYLUoCAUI"
    - "BjsaUsALEzY"
    - "tmY2SzWzrtk"
    - "B0NWSPdj6bI"
    - "R2exHIAxRFY"
    - "suuaQacgYHI"
    - "3HlaqBnwYnc"
youtube_channels:
  - url: "https://www.youtube.com/@Qixiang-Animation/videos"

bilibili_accounts:
  account1:
    username: "ghDjd4JW2Fy9ecRq@gmail.com"
    userid: "1256596736"
    cookies_file: "./cookies/blbl_1.txt"