youtube:
  cookies_file: "./cookies/yt_12.txt" #zhaojson71@gmail.com
  video_limit_before_rest: 50  # 成功下载多少个视频后休息（0 表示不限制）
  concurrent_fragments: 2  # 并发下载片段数，提高下载速度
  sleep_interval_seconds: 30  # 睡眠间隔时间（秒）
  video_limit_rest_duration: 120  # 休息时长（分钟），默认1小时，实际休息时间会在此基础上随机增加 0-10%
  video_ids:
  - "_o3auL2_Im8"
  - "DKDgB4zhqUk"
  - "k8nZWXhwefs"  
  - "jZf898jEf4Y"
  - "hJth5EO2V0c"
  - "xwQqNGQYFXY"
  - "iqco0M9Bo6I"
  - "JMSU5IgrVvk"
  - "Aeozr0a5ugQ"
  - "S8F5maMCsr8"
  - "_E7O3HP1UR8"
  - "7N8FG8i6Ptc"
  - "S8b_cw7WLeo"
  - "rq05G_7grEk"
  - "JzVPqiTw_9g"
  - "gBefBuJp1-k"
  - "WTMHBKhjr64"
  - "oNqDrtsWNHI"
  - "TDRb9OpvALg"
  - "UBESOXkyYS4"
  - "ktQcOeBBckQ"
  - "UduVER9eeTc"
  - "puGXq9Wthrg"
  - "oFL_kgTifQ8"
  - "1atxcvWdP7E"
  - "aTso25Jsb84"
  - "OkMngaH4nQM"
  - "q0uUhEFCDJo"
  - "XSOJc1tbDuo"
  - "d6w-nHn2u_A"
  - "86nJzWHoPKU"
  - "cIIHPe85c-I"
  - "hV3Vv-fyGOs"
  - "PNlA3_U3eU4"
  - "R5lb_5Z6Gfg"
  - "IILq4Vmh5NI"
  - "UE7BXi3YSbA"
  - "L-p1IfkmD4I"
  - "Z12-6i4Ws-k"
  - "apn_FPFbwnU"
  - "YV0fPxVW3ww"
  - "pbwZCfrQ4dg"
  - "0WErtt4_V8M"
youtube_channels:
  - url: "https://www.youtube.com/@Qixiang-Animation/videos"
  #   languages: ["en", "id", "my", "th", "zh-Hans"]  # Qixiang-Animation  8680
  #   limit: 400
  #   offset: 4400
  - url: "https://www.youtube.com/@%E9%AD%94%E5%8A%9B%E5%8B%95%E6%BC%AB/videos"

bilibili_accounts:
  account2:
    username: "beMcfuS9ogcHWD2S@gmail.com"
    userid: "1256654608"
    cookies_file: "./cookies/blbl_2.txt"
