youtube:
  cookies_file: "./cookies/yt_7.txt" # jimmy7zhou@gmail.com
  video_limit_before_rest: 50  # 成功下载多少个视频后休息（0 表示不限制）
  concurrent_fragments: 2  # 并发下载片段数，提高下载速度
  sleep_interval_seconds: 30  # 睡眠间隔时间（秒）
  video_limit_rest_duration: 120  # 休息时长（分钟），默认1小时，实际休息时间会在此基础上随机增加 0-10%
  sleep_requests_seconds: 0
  sleep_subtitles_seconds: 0  
youtube_channels:
  - url: "https://www.youtube.com/@%E6%9B%BC%E6%B3%A2%E5%8B%95%E6%BC%AB/videos"
  - url: "https://www.youtube.com/@Comic-likerhythm/videos"
  - url: "https://www.youtube.com/@%E7%A5%9E%E9%BE%8D%E6%BC%AB%E7%A0%94%E7%A4%BE/videos"
  - url: "https://www.youtube.com/@%E5%8B%95%E6%BC%AB%E6%A0%B8%E7%88%86%E5%B1%80-manju/videos"
  - url: "https://www.youtube.com/@AnimeDragon77/videos"
  - url: "https://www.youtube.com/@%E9%AD%94%E5%8A%9B%E5%8B%95%E6%BC%AB/videos"
  - url: "https://www.youtube.com/@Qixiang-Animation/videos"

bilibili_accounts:
  account7:
    username: "om4ZDAa0QWyfyqdl@gmail.com"
    userid: "1257023168"
    cookies_file: "./cookies/blbl_7.txt"
