youtube:
  cookies_file: "./cookies/yt_8.txt" # jimmy.08.zhou@gmail.com
  video_limit_before_rest: 50  # 成功下载多少个视频后休息（0 表示不限制）
  concurrent_fragments: 2  # 并发下载片段数，提高下载速度
  sleep_interval_seconds: 30  # 睡眠间隔时间（秒）
  video_limit_rest_duration: 120  # 休息时长（分钟），默认1小时，实际休息时间会在此基础上随机增加 0-10%
  video_ids: # 8
    - "u5r7VwSsrvA"
    - "hkSGifHS0QM"
    - "66bYVjKsfNc"
    - "KXHfW-bDSZk"
    - "KDEFGcLYpqQ"
    - "xdqJWB2aVD4"
    - "MAQcroPF5lg"
    - "JhJXtQfT8OA"
    - "Zgy5yPMmQC8"
    - "suaSMu-aljg"
    - "wQvESRE6gJ8"
    - "5POWYKQ5wKE"
    - "FaJzn4SZV3U"
    - "81aUQ_wjOSE"
    - "xdqJWB2aVD4"
    - "W6QeK0I_jLw"
    - "_fCMRL-ct40"
    - "Taj6f2Y8t70"
    - "z9UBm7iW3Jo"
    - "xyJrvopEolA"
    - "7mAx5bGwn0Q"
    - "h5blTqGlUco"
youtube_channels:
  - url: "https://www.youtube.com/@Qixiang-Animation/videos"

bilibili_accounts:
  account8:
    username: "wyTGIkNBoY5yYgre@gmail.com"
    userid: "1257080192"
    cookies_file: "./cookies/blbl_8.txt"
